import {
  product1,
  product2,
  product3,
  product4,
  product5,
  product6,
  product7,
  product8,
  product9,
  product10,
} from '@app/assets/images';
import {ProductsResponse} from '@app/types';

export const products: ProductsResponse = [
  {
    id: 1,
    name: 'Pizza',
    description: 'Delicious pizza from Italy with a lot of toppings',
    photo: product1,
    quantity: 130,
    capital: 5000,
    price: 10000,
    discount: 0,
    barcode: '123456789',
    variants: [
      {size: 'M', crust: 'Thin', price: 11.99, stock: 80},
      {size: 'L', crust: 'Thick', price: 15.99, stock: 50},
    ],
  },
  {
    id: 2,
    name: 'Burger',
    description: 'Juicy beef burger with cheddar cheese and fresh lettuce',
    photo: product2,
    quantity: 80,
    capital: 3000,
    price: 35000,
    discount: 10,
    barcode: '987654321',
    variants: [
      {size: 'Single', bun: 'Sesame', price: 8.99, stock: 40},
      {size: 'Double', bun: 'Brioche', price: 12.99, stock: 30},
    ],
  },
  {
    id: 3,
    name: 'Sushi Set',
    description: 'Assorted sushi set with fresh salmon, tuna, and shrimp',
    photo: product3,
    quantity: 50,
    capital: 7000,
    price: 12000,
    discount: 5,
    barcode: '456789123',
    variants: [
      {type: 'Classic', servings: '10 pieces', price: 19.99, stock: 25},
      {type: 'Premium', servings: '15 pieces', price: 29.99, stock: 15},
    ],
  },
  {
    id: 4,
    name: 'Spaghetti',
    description: 'Traditional Italian spaghetti with rich tomato sauce',
    photo: product4,
    quantity: 100,
    capital: 4000,
    price: 5600,
    discount: 7,
    barcode: '321654987',
    variants: [
      {size: 'Regular', sauce: 'Tomato', price: 10.99, stock: 60},
      {size: 'Large', sauce: 'Meat', price: 14.99, stock: 40},
    ],
  },
  {
    id: 5,
    name: 'Taco',
    description: 'Crispy tacos filled with beef and fresh vegetables',
    photo: product5,
    quantity: 70,
    capital: 2500,
    price: 56000,
    discount: 0,
    barcode: '789123456',
    variants: [
      {size: 'Small', filling: 'Beef', price: 5.99, stock: 30},
      {size: 'Large', filling: 'Chicken', price: 7.99, stock: 20},
    ],
  },
  {
    id: 6,
    name: 'Ice Cream',
    description: 'Creamy ice cream available in multiple flavors',
    photo: product6,
    quantity: 200,
    capital: 1500,
    price: 9000,
    discount: 12,
    barcode: '147258369',
    variants: [
      {flavor: 'Vanilla', size: 'Medium', price: 3.99, stock: 100},
      {flavor: 'Chocolate', size: 'Large', price: 5.99, stock: 80},
    ],
  },
  {
    id: 7,
    name: 'Fried Chicken',
    description: 'Crispy fried chicken with secret herbs and spices',
    photo: product7,
    quantity: 90,
    capital: 6000,
    price: 345000,
    discount: 15,
    barcode: '369258147',
    variants: [
      {piece: 'Wing', spiceLevel: 'Mild', price: 6.99, stock: 45},
      {piece: 'Leg', spiceLevel: 'Hot', price: 7.99, stock: 35},
    ],
  },
  {
    id: 8,
    name: 'Pasta',
    description: 'Creamy Alfredo pasta with parmesan cheese',
    photo: product8,
    quantity: 60,
    capital: 3500,
    price: 44000,
    discount: 8,
    barcode: '741852963',
    variants: [
      {size: 'Medium', type: 'Fettuccine', price: 9.99, stock: 30},
      {size: 'Large', type: 'Spaghetti', price: 13.99, stock: 20},
    ],
  },
  {
    id: 9,
    name: 'Salad',
    description: 'Fresh garden salad with organic veggies',
    photo: product9,
    quantity: 110,
    capital: 2000,
    price: 23000,
    discount: 3,
    barcode: '963852741',
    variants: [
      {size: 'Small', dressing: 'Vinaigrette', price: 4.99, stock: 50},
      {size: 'Large', dressing: 'Ranch', price: 7.99, stock: 40},
    ],
  },
  {
    id: 10,
    name: 'Smoothie',
    description: 'Healthy fruit smoothies made fresh daily',
    photo: product10,
    quantity: 120,
    capital: 1800,
    price: 11000,
    discount: 5,
    barcode: '852963741',
    variants: [
      {flavor: 'Mango', size: 'Medium', price: 5.99, stock: 60},
      {flavor: 'Berry', size: 'Large', price: 7.99, stock: 45},
    ],
  },
];
