name: Build and Upload APK to VPS

on:
  push:
    branches:
      - main    # Trigger on push to the main branch
      - dev     # Trigger on push to the dev branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository to get the source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java 21 for React Native build
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Set up Node.js v22 for React Native
      - name: Set up Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          yarn: true  # This installs Yarn on the runner

      # Step 4: Install dependencies using Yarn
      - name: Install dependencies with Yarn
        run: yarn install --ignore-engines

      # Step 5: Build the APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      # Step 6: Set up the SSH private key from GitHub secrets
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa  # Use the secret for the private key
          chmod 600 ~/.ssh/id_rsa  # Set correct file permissions

      # Step 7: Upload the APK file to the VPS using SCP
      - name: Upload APK to VPS
        run: |
          scp -o StrictHostKeyChecking=no android/app/build/outputs/apk/release/app-release.apk root@46.250.237.92:/root/apks/
