name: Build and Upload APK to VPS

on:
  push:
    branches:
      - main    # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository to get the source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java 21 for React Native build
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Set up Node.js v22 for React Native
      - name: Set up Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          yarn: true  # Install Yarn

      # Step 4: Install dependencies using Yarn
      - name: Install dependencies with Yarn
        run: yarn install --ignore-engines

      # Step 5: Set up environment variables for React Native build
      - name: Set up .env file
        run: |
          echo "API_URL=http://46.250.237.92:3000/api" > .env

      # Step 6: List all files to verify the .env file is created
      - name: List all files
        run: ls -a  # This will list all files, including hidden files like .env

      - name: Clean build
        run: |
          cd android
          ./gradlew clean

      # Step 7: Build the APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      # Step 8: Set up the SSH private key from GitHub secrets
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 9: Upload the APK file to the VPS using SCP
      - name: Upload APK to VPS
        run: |
          scp -o StrictHostKeyChecking=no android/app/build/outputs/apk/release/*-release.apk root@46.250.237.92:/var/www/html/apks/

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export PATH=$PATH:/usr/local/bin:/root/.nvm/versions/node/v22.14.0/bin

            # ✅ Generate Git commit history JSON with clock
            node -e "
              const fs = require('fs');
              const { execSync } = require('child_process');
              
              // Run git log to get the commit history with ISO date format
              const log = execSync('git log --pretty=format:\\'%h|%an|%ad|%s\\' --date=iso').toString();  // --date=iso for detailed timestamps

              // Parse each line of the log and extract the commit details
              const commits = log.split('\\n').map(l => {
                const [hash, author, date, message] = l.split('|');
                
                // Add a clock field using the actual commit date and format it to a readable time
                const clock = new Date(date).toLocaleTimeString('en-US', {
                  hour: '2-digit',
                  minute: '2-digit',
                  second: '2-digit',
                  hour12: true
                });

                return { hash, author, date, message, clock };
              });

              // Write the commit data to a JSON file
              fs.writeFileSync('commits.json', JSON.stringify(commits, null, 2));
            "


            # ✅ Copy to web-accessible directory
            cp commits.json /var/www/html/apks/commits-ui.json